[project]
name = "yt-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg>=1.4",
    "streamlit>=1.46.1",
    "yt-dlp>=2025.6.30",
]
